### ISSUE TITLE
Migrate freeCodeCamp/strip-comments to TypeScript

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/curriculum-helpers#180]
It would be helpful if we provided declaration files for anyone wanting to use this in a TypeScript project.  This should be something we can do automatically via https://www.typescriptlang.org/tsconfig#declaration

Most of the work has already been done in https://github.com/freeCodeCamp/curriculum-helpers/pull/46, but those changes will need reimplementing here.

**Comment by a2937** [comment]
Hey. What library are we going to use bundle up the source? I saw something about `rollup`.

**Comment by ojeytonwilliams** [comment]
Given that this has sat here untouched for two years, it's safe to conclude that we're not going to maintain this adequately as a separate repo.

@a2937 thanks for looking into this and making a PR, but I think we should deprecate this repo instead and concentrate on the curriculum-helpers.
